### ISSUE TITLE
Revised Phase One

### ISSUE THREAD

**Issue by prcastro** [brk00/simplex-phase2#10]
It's faillng, we need to fix it.

**Comment by lssimoes** [comment]
Fixed by e672bdc3a617a4452c11a5e70c1b66d9a7a47581, although we are still having some other unknown issue possibly correlated

**Comment by prcastro** [comment]
I believe Binv is not being updated correctly, because when I try (inside `revisedReducedCosts`) to compare:

``` matlab
Binv == inv(A(:,bind))
```

They are different.

**Comment by prcastro** [comment]
Fixed with 6fa7aa599aab7829b6f40a188d87046143d28e62
