### ISSUE TITLE
Reduced costs: row or column vector?

### ISSUE THREAD

**Issue by prcastro** [brk00/simplex-phase2#2]
On line 16 we compute:

``` octave
p'*A(:, nbind)
```

And this gives us a row vector. This line vector is subtracted from `c(nbind)`, that is a column vector. There is, therefore, an error, since we would expect `p'*A(:, nbind)` to also result on a column vector.

Is anything wrong with our `p`?

**Comment by prcastro** [comment]
Or maybe we just transpose `c(nbind)` so it becomes a row vector

**Comment by lssimoes** [comment]
Hm strange, as far as I see it, we have 

``` latex
\bar{c_j} = c_j - c_B^T B^{-1} A_j
```

our reduced costs vector. So we did

``` latex
p^T = c_B^T B^{-1}  =>  c_B = (LU)^T p = U^T L^T p
```

Going back, I'm pretty sure `c_B^T B^{-1} A_j` should get us a column vector, since it will be the subtracted from `c_j`.. Not sure about what's going on

**Comment by lssimoes** [comment]
Sorry, my bad. `c_B^T B^{-1} A_j` is clearly a real number, since `B^{-1}` is a matrix and `A_j` is a column vector.
We are probably getting something wrong when why try to stack our reduced costs for different `j`'s on a vector

**Comment by prcastro** [comment]
This means `p' * A(:, nbind)` is a row vector?

**Comment by lssimoes** [comment]
Exactly. For us to stack ou `c_j`'s into a column vector we should first transpose this multiplication

**Comment by prcastro** [comment]
I woudn't care if our `redc` is a row vector as it is right now.

This "problem" is a little bit strange for me since the `j`-th reduced cost is defined as:

```
\bar{c_j} = c_j - c_b' B^{-1} A_j
```

But suppose we have not one, but many `j`s. `A_j` clearly becomes a matrix with the columns of `A` respective to each `j`.

But what happens to `c_j`? It becomes a row vector? A column vector? I believe we are free to choose it to be compatible with the right hand side. This is what we did: we chose it to be a row vector.

**Comment by lssimoes** [comment]
Well, in my opinion it would be clearer if `c_j` became a column vector. The idea of a row vector kind of disturbes me.
Maybe the code will get a little bit strange because of the transposition we will need to do, but I guess the mathematical intuition behind will be much better

**Comment by prcastro** [comment]
I don't agree that it's more natural for it to be a column vector: when we work with many `j`s, we group the `A_j`s horizontally. Why shouldn't we do the same with the `c_j`s?

**Comment by prcastro** [comment]
For me, it's unnatural to transpose an entire operand (`p'*A(:, nbind)`) that we **know** to be a row vector. Not to say it's cheaper to transpose `c(nbind)`.

**Comment by lssimoes** [comment]
Ok, you have a point there. I just don't like to have a row vector that isn't a transposed one.
Actually, our operation wasn't naturally the one that we are doing now, but since we already choose this one..

**Comment by prcastro** [comment]
Vectorizing this kind of operation is not natural for me neither. Once we port the code to Julia, I belive it's better to do it by constructing a column vector inside a `for` loop. We just can't afford the overhead in Octave.
