### ISSUE TITLE
Julia port

### ISSUE THREAD

**Issue by prcastro** [brk00/simplex-phase2#4]
We should port the code to Julia, and most certainly get better performance.

**Comment by lssimoes** [comment]
Indeed we have. Have you already benchmarked our Octave code?

**Comment by prcastro** [comment]
Not yet, I believe Julia will shine only on larger problems, but we are lacking this kind of example right now.

Also, we should disable the printing when doing benchmarks. As we discussed before, Octave has a huge overhead with passing arrays to printing functions.

**Comment by prcastro** [comment]
Solved by 87ce1a999c7288396b59eabb12366a87453daa3e and baefd5a871df76524886f1f4dbbef70f0dbf994c
